ebook_website/Controllers/LivresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ebook_website.Models;

namespace ebook_website.Controllers
{
    public class LivresController : Controller
    {
        private ebookEntities db = new ebookEntities();

        // GET: Admin/Livres
        public ActionResult Index(string SearchName)
        {
            return View(db.Livre.Where(c => c.Titre.Contains(SearchName)
          || c.Auteur.Contains(SearchName) || c.Categorie.Nom_Categorie.Contains(SearchName)
            || c.Description.Contains(SearchName) || SearchName == null).ToList());
        }
        //public ActionResult Index(DateTime Searchdate)
        //{
        //    return View(db.Livre.Where(c =>(c.Date_Edition.Equals(Searchdate))|| c.Date_Publication.Equals(Searchdate) 
        //    || Searchdate == null).ToList());
        //}

        // GET: Admin/Livres/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["access"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Livre livre = db.Livre.Find(id);
                Session["imgPath"] = livre.Image;
                Session["pdfPath"] = livre.PDF;
                if (livre == null)
                {
                    return HttpNotFound();
                }
                return View(livre);
            }
            else
                return RedirectToAction("Login", "Admin");
        }

        // GET: Admin/Livres/Create
        public ActionResult Create()
        {
            if (Session["access"] != null)
            {
                ViewBag.ID_Categorie = new SelectList(db.Categorie, "ID_Categorie", "Nom_Categorie");
                return View();
            }
            else
                return RedirectToAction("Login", "Admin");
        }

        // POST: Admin/Livres/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Livre livre, HttpPostedFileBase upload, HttpPostedFileBase file)
        {
            if (Session["access"] != null)
            {
                if (file == null)
                {
                    ModelState.AddModelError("Erreur", "S'il vous plait selectionnez un fichier Doc/Pdf seulement");
                    return View(livre);
                }
                if (!(file.ContentType == "application/msword" || file.ContentType == "application/pdf"))
                {
                    ModelState.AddModelError("Erreur", "S'il vous plait selectionnez seulement fichier Doc ou Pdf !");
                    return View(livre);
                }
                if (ModelState.IsValid)
                {
                    string pat = Path.Combine(Server.MapPath("~/Uploads/Livres/PDF/"), file.FileName);
                    file.SaveAs(pat);
                    livre.PDF = file.FileName;


                    //Upload image 
                    string filename = Path.GetFileName(upload.FileName);
                    string _filename = DateTime.Now.ToString("yymmssfff") + filename;
                    string extension = Path.GetExtension(upload.FileName);
                    string path = Path.Combine(Server.MapPath("~/Uploads/Livres/"), _filename);
                    livre.Image = "~/Uploads/Livres/" + _filename;
                    if (extension.ToLower() == ".jpg" || extension.ToLower() == ".jpeg" || extension.ToLower() == ".png")
                    {
                        if (upload.ContentLength <= 1000000)
                        {
                            db.Livre.Add(livre);
                            if (db.SaveChanges() > 0)
                            {
                                upload.SaveAs(path);
                            }
                        }
                    }
                    return RedirectToAction("Index");
                }
                ViewBag.ID_Categorie = new SelectList(db.Categorie, "ID_Categorie", "Nom_Categorie", livre.ID_Categorie);
                return View(livre);
            }
            else
                return RedirectToAction("Login", "Admin");
        }

        // GET: Admin/Livres/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["access"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Livre livre = db.Livre.Find(id);
                Session["imgPath"] = livre.Image;
                if (livre == null)
                {
                    return HttpNotFound();
                }
                ViewBag.ID_Categorie = new SelectList(db.Categorie, "ID_Categorie", "Nom_Categorie", livre.ID_Categorie);
                return View(livre);
            }
            else
                return RedirectToAction("Login", "Admin");
        }

        // POST: Admin/Livres/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_Livre,Titre,Auteur,Description,Date_Publication,Date_Edition,ID_Categorie,Image,PDF")] Livre livre, HttpPostedFileBase upload)
        {
            if (Session["access"] != null)
            {
                if (ModelState.IsValid)
                {
                    //db.Entry(livre).State = EntityState.Modified;
                    //db.SaveChanges();
                    //return RedirectToAction("Index");
                    if (upload != null)
                    {
                        string filename = Path.GetFileName(upload.FileName);
                        string _filename = DateTime.Now.ToString("yymmssfff") + filename;
                        string extension = Path.GetExtension(upload.FileName);
                        string path = Path.Combine(Server.MapPath("~/Uploads/Livres"), _filename);
                        livre.Image = "~/Uploads/Livres/" + _filename;
                        if (extension.ToLower() == ".jpg" || extension.ToLower() == ".jpeg" || extension.ToLower() == ".png")
                        {
                            if (upload.ContentLength <= 1000000)
                            {
                                db.Entry(livre).State = EntityState.Modified;
                                string oldImagePath = Request.MapPath(Session["imgPath"].ToString());
                                //db.Categorie.Add(categorie);
                                if (db.SaveChanges() > 0)
                                {
                                    upload.SaveAs(path);
                                    if (System.IO.File.Exists(oldImagePath))
                                    {
                                        System.IO.File.Delete(oldImagePath);
                                    }
                                }
                            }
                        }
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        livre.Image = Session["imgPath"].ToString();
                        db.Entry(livre).State = EntityState.Modified;
                        return RedirectToAction("Index");
                    }
                }
                ViewBag.ID_Categorie = new SelectList(db.Categorie, "ID_Categorie", "Nom_Categorie", livre.ID_Categorie);
                return View(livre);
            }
            else
                return RedirectToAction("Login", "Admin");
        }

        // GET: Admin/Livres/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["access"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Livre livre = db.Livre.Find(id);
                Session["imgPath"] = livre.Image;
                if (livre == null)
                {
                    return HttpNotFound();
                }
                return View(livre);
            }
            else
                return RedirectToAction("Login", "Admin");
        }

        // POST: Admin/Livres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (Session["access"] != null)
            {
                Livre livre = db.Livre.Find(id);

                db.Livre.Remove(livre);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
                return RedirectToAction("Login", "Admin");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ebook_website/Controllers/UtilisateursController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ebook_website.Models;

namespace ebook_website.Controllers
{
    public class UtilisateursController : Controller
    {
        private ebookEntities db = new ebookEntities();

        // GET: Utilisateurs
        public ActionResult Index(string SearchName)
        {
            if (Session["access"] != null)
            {
                return View(db.Utilisateur.Where(c => c.Email.Contains(SearchName)
                 || c.Nom.Contains(SearchName) || c.Prenom.Contains(SearchName) || SearchName == null).ToList());
            }
            else
                return RedirectToAction("Login", "Admin");
        }

        // GET: Utilisateurs/Details/5
        public ActionResult Details(string id)
        {
            if (Session["access"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Utilisateur utilisateur = db.Utilisateur.Find(id);
                if (utilisateur == null)
                {
                    return HttpNotFound();
                }
                return View(utilisateur);
            }
            else
                return RedirectToAction("Login", "Admin");
        }

        // GET: Utilisateurs/Create
        public ActionResult Create()
        {
            if (Session["access"] != null)
            {
                return View();
            }
            else
                return RedirectToAction("Login", "Admin");
        }

        // POST: Utilisateurs/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Nom,Prenom,Email,Password")] Utilisateur utilisateur)
        {
            if (Session["access"] != null)
            {
                if (ModelState.IsValid)
                {
                    db.Utilisateur.Add(utilisateur);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                return View(utilisateur);
            }
            else
                return RedirectToAction("Login", "Admin");
        }

        // GET: Utilisateurs/Edit/5
        public ActionResult Edit(string id)
        {
            if (Session["access"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Utilisateur utilisateur = db.Utilisateur.Find(id);
                if (utilisateur == null)
                {
                    return HttpNotFound();
                }
                return View(utilisateur);
            }
            else
                return RedirectToAction("Login", "Admin");
        }

        // POST: Utilisateurs/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Nom,Prenom,Email,Password")] Utilisateur utilisateur)
        {
            if (Session["access"] != null)
            {
                if (ModelState.IsValid)
                {
                    db.Entry(utilisateur).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(utilisateur);
            }
            else
                return RedirectToAction("Login", "Admin");
        }

        // GET: Utilisateurs/Delete/5
        public ActionResult Delete(string email)
        {
            if (Session["access"] != null)
            {
                if (email == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Utilisateur utilisateur = db.Utilisateur.Find(email);
                if (utilisateur == null)
                {
                    return HttpNotFound();
                }
                return View(utilisateur);
            }
            else
                return RedirectToAction("Login", "Admin");
        }

        // POST: Utilisateurs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string email)
        {
            if (Session["access"] != null)
            {
                Utilisateur utilisateur = db.Utilisateur.Find(email);
                db.Utilisateur.Remove(utilisateur);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
                return RedirectToAction("Login", "Admin");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ebook_website/Controllers/conctactsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ebook_website.Models;

namespace ebook_website.Controllers
{[Authorize]
    public class conctactsController : Controller
    {
        private ebookEntities db = new ebookEntities();

        // GET: conctacts
        public ActionResult Index()
        {
            return View(db.conctact.ToList());
        }

        // GET: conctacts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            conctact conctact = db.conctact.Find(id);
            if (conctact == null)
            {
                return HttpNotFound();
            }
            return View(conctact);
        }

        

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ebook_website/Views/Shared/_Footer.cshtml
<div class="footer fixed-bottom " style=" bottom: 0; color: gold; font-family: Verdana; font-size: 18px; padding: 20px; background-color: black; box-shadow: 10px 0px 5px gray;">

    <div style="text-align:center; font-size:15px;">
        All Copyright &copy; are reserved - E-book
    </div>
    <!--Lila-->
</div>

ebook_website/Views/Shared/_Header.cshtml
<style>
    #ebook{
        text-decoration:none;
    }
</style>
<nav id="mynav" class="navbar navbar-expand-lg navbar-dark fixed-top">
    <div class="container">
        <div> @Html.ActionLink("E-Book", "home", "Test", new { @id = "ebook" })</div>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fa fa-bars ml-1"></i>
        </button>
        <div class="collapse navbar-collapse " id="navbarResponsive">
            <ul class="navbar-nav text-uppercase ml-auto" style="float:right">
                @if (User.Identity.IsAuthenticated && Session["email"] != null)
                {
                    <li class="nav-item "> @Html.ActionLink("Nos livres", "afterLogin", "Test", new { @class = "itemLink nav-link " })</li>
                    <li class="nav-item "> @Html.ActionLink("contactez-nous", "contact", "Test", new { @class = "itemLink nav-link " })</li>
                    <li class="nav-item "> @Html.ActionLink("Profile", "profilee", "Test", new { @class = "itemLink nav-link " })</li>
                    <li class="nav-item "> @Html.ActionLink("Se déconnecter", "logout", "Test", new { @class = "itemLink nav-link " })</li>
                }
                else
                {

                    <li class="nav-item"> <a class=" itemLink nav-link" href="~/test/login"><i class="far fa-user" style="color:gold; font-weight:bold"></i> Se Connecter</a></li>
                    <li class="nav-item"> <a class=" itemLink nav-link" href="~/test/register"><i class="fas fa-user-plus" style="color: gold; font-weight: bold"></i> Créer mon compte</a></li>
                }

            </ul>
        </div>
    </div>
</nav>
<br />
<br />

ebook_website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>E-BOOK Administration</title>
    <link href="~/css/styles.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>
</head>


<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark fixed-top">
        <button class="btn" style="background-color:#343a40" type="button" data-toggle="collapse" data-target="#Barre" aria-expanded="false" aria-controls="collapseExample">
            <i class="fas fa-bars" style="color:#fb4979"></i>
        </button>
        <a style="color:#fb4979" class="navbar-brand" href="~/categories/index">E-Book Administration</a>

        <!-- Navbar Search-->
        <!-- Navbar-->
        <ul class="navbar-nav ml-auto ml-auto">
            <li class="nav-item dropdown">
                @*<a class="nav-link dropdown-toggle" id="userDropdown" href="#!" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>*@
                <i class="fas fa-user" style="color:#fb4979;margin-right:5px"></i> @Html.Partial("_login")

            </li>
            @*<div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#!">Settings</a>
                <a class="dropdown-item" href="#!">Activity Log</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="login.html">Logout</a>
            </div>*@
        </ul>
    </nav>
    <br />
    <br />
    <br />
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu collapse" id="Barre">
                    <div class="nav">

                        @*<a class="nav-link collapsed" href="@Url.Action("Index","Categories")" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
            Catégories
            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
        </a>*@
                        <a class="nav-link" href="@Url.Action("Index","Categories")">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            Catégories
                        </a>
                        <a class="nav-link" href="@Url.Action("Index","Livres")">
                            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                            Livres
                            @*<div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>*@
                        </a>
                        <a class="nav-link" href="@Url.Action("Index","Utilisateurs")">
                            <div class="sb-nav-link-icon">
                                @*<i class="fas fa-chart-area"></i>*@
                                <i class="fas fa-users fa-fw"></i>
                            </div>

                            Utilisateurs
                        </a>

                        <a class="nav-link" href="@Url.Action("EditProfile","Profile")">
                            <div class="sb-nav-link-icon">
                                @*<i class="fas fa-chart-area"></i>*@
                                <i class="fas fa-user fa-fw"></i>
                            </div>
                            Profile
                        </a>
                        <a class="nav-link" href="@Url.Action("Index","conctacts")">
                            <div class="sb-nav-link-icon"><i class="far fa-comment-dots"></i></div>
                            Contacts
                        </a>
                        <a class="nav-link" href="@Url.Action("Login","admin")">
                            <div class="sb-nav-link-icon"><i class="fas fa-sign-out-alt"></i></div>
                            Se déconnecter
                        </a>
                    </div>
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid">

                    @*<ol class="breadcrumb mb-4">
                            <li class="breadcrumb-item active">Tableau de bord </li>
                        </ol>*@
                    @RenderBody()
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto fixed-bottom">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; E-BOOK 2021</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/js/scripts.js"></script>
    <script src="~/assets/demo/datatables-demo.js"></script>
    <script src="~/assets/demo/chart-pie-demo.js"></script>
    <script src="~/assets/demo/chart-bar-demo.js"></script>
    <script src="~/assets/demo/chart-area-demo.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>

    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>


</body>
</html>

ebook_website/Views/Shared/_MyDefaultPage.cshtml
<!DOCTYPE html>
<html>
<head>

    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/jquery-3.0.0.min.js"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/Content/Site.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">


    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
    <title>@Page.Title</title>
    @RenderSection("head", required: false)
</head>
<body>

    @RenderPage("_Header.cshtml")
    <div class="container body-content" >
        @RenderBody()
    </div>
    <br /><br />
    @RenderPage("_Footer.cshtml")

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Third party plugin JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/3.2.1/anime.min.js"></script>
    <!-- Contact form JS-->
    <script src="assets/mail/jqBootstrapValidation.js"></script>
    <script src="assets/mail/contact_me.js"></script>
    <!-- Core theme JS-->
    <script src="js/scripts.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    <script>
        var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
        var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
            return new bootstrap.Tooltip(tooltipTriggerEl)
        })
    </script>
</body>

</html>

ebook_website/Views/Shared/_login.cshtml
@if (User.Identity.IsAuthenticated)
{
    <li style="color:white;">@User.Identity.Name</li>
}
else
{
    <li>@Html.ActionLink("Login", "Login", "Login")</li>
}